// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: stock/stock.proto

package stock

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_stock_stock_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{0}
}

func (x *GetQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         *Quote                 `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_stock_stock_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuoteResponse) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

type ListQuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesRequest) Reset() {
	*x = ListQuotesRequest{}
	mi := &file_stock_stock_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesRequest) ProtoMessage() {}

func (x *ListQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesRequest.ProtoReflect.Descriptor instead.
func (*ListQuotesRequest) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{2}
}

func (x *ListQuotesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type ListQuotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quotes        []*Quote               `protobuf:"bytes,1,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesResponse) Reset() {
	*x = ListQuotesResponse{}
	mi := &file_stock_stock_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesResponse) ProtoMessage() {}

func (x *ListQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesResponse.ProtoReflect.Descriptor instead.
func (*ListQuotesResponse) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{3}
}

func (x *ListQuotesResponse) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type SearchStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStocksRequest) Reset() {
	*x = SearchStocksRequest{}
	mi := &file_stock_stock_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStocksRequest) ProtoMessage() {}

func (x *SearchStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStocksRequest.ProtoReflect.Descriptor instead.
func (*SearchStocksRequest) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{4}
}

func (x *SearchStocksRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchStocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*StockInfo           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchStocksResponse) Reset() {
	*x = SearchStocksResponse{}
	mi := &file_stock_stock_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchStocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchStocksResponse) ProtoMessage() {}

func (x *SearchStocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchStocksResponse.ProtoReflect.Descriptor instead.
func (*SearchStocksResponse) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{5}
}

func (x *SearchStocksResponse) GetResults() []*StockInfo {
	if x != nil {
		return x.Results
	}
	return nil
}

type StockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ShortName     string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Exchange      string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockInfo) Reset() {
	*x = StockInfo{}
	mi := &file_stock_stock_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockInfo) ProtoMessage() {}

func (x *StockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockInfo.ProtoReflect.Descriptor instead.
func (*StockInfo) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{6}
}

func (x *StockInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StockInfo) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *StockInfo) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *StockInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListSymbolsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "B3", "US" ou "" para todos
	Exchange      string `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsRequest) Reset() {
	*x = ListSymbolsRequest{}
	mi := &file_stock_stock_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsRequest) ProtoMessage() {}

func (x *ListSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsRequest.ProtoReflect.Descriptor instead.
func (*ListSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{7}
}

func (x *ListSymbolsRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type ListSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []*StockInfo           `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSymbolsResponse) Reset() {
	*x = ListSymbolsResponse{}
	mi := &file_stock_stock_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSymbolsResponse) ProtoMessage() {}

func (x *ListSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSymbolsResponse.ProtoReflect.Descriptor instead.
func (*ListSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{8}
}

func (x *ListSymbolsResponse) GetSymbols() []*StockInfo {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *ListSymbolsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ShortName     string                 `protobuf:"bytes,2,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Change        float64                `protobuf:"fixed64,4,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,5,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_stock_stock_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_stock_stock_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_stock_stock_proto_rawDescGZIP(), []int{9}
}

func (x *Quote) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Quote) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Quote) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Quote) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *Quote) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

func (x *Quote) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_stock_stock_proto protoreflect.FileDescriptor

const file_stock_stock_proto_rawDesc = "" +
	"\n" +
	"\x11stock/stock.proto\x12\x05stock\")\n" +
	"\x0fGetQuoteRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"6\n" +
	"\x10GetQuoteResponse\x12\"\n" +
	"\x05quote\x18\x01 \x01(\v2\f.stock.QuoteR\x05quote\"-\n" +
	"\x11ListQuotesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\":\n" +
	"\x12ListQuotesResponse\x12$\n" +
	"\x06quotes\x18\x01 \x03(\v2\f.stock.QuoteR\x06quotes\"+\n" +
	"\x13SearchStocksRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"B\n" +
	"\x14SearchStocksResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.stock.StockInfoR\aresults\"r\n" +
	"\tStockInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"0\n" +
	"\x12ListSymbolsRequest\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\"W\n" +
	"\x13ListSymbolsResponse\x12*\n" +
	"\asymbols\x18\x01 \x03(\v2\x10.stock.StockInfoR\asymbols\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xb1\x01\n" +
	"\x05Quote\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x16\n" +
	"\x06change\x18\x04 \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\x05 \x01(\x01R\rchangePercent\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp2\x9d\x02\n" +
	"\fStockService\x12;\n" +
	"\bGetQuote\x12\x16.stock.GetQuoteRequest\x1a\x17.stock.GetQuoteResponse\x12A\n" +
	"\n" +
	"ListQuotes\x12\x18.stock.ListQuotesRequest\x1a\x19.stock.ListQuotesResponse\x12G\n" +
	"\fSearchStocks\x12\x1a.stock.SearchStocksRequest\x1a\x1b.stock.SearchStocksResponse\x12D\n" +
	"\vListSymbols\x12\x19.stock.ListSymbolsRequest\x1a\x1a.stock.ListSymbolsResponseB,Z*github.com/piovani/stock_exchange/pb/stockb\x06proto3"

var (
	file_stock_stock_proto_rawDescOnce sync.Once
	file_stock_stock_proto_rawDescData []byte
)

func file_stock_stock_proto_rawDescGZIP() []byte {
	file_stock_stock_proto_rawDescOnce.Do(func() {
		file_stock_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stock_stock_proto_rawDesc), len(file_stock_stock_proto_rawDesc)))
	})
	return file_stock_stock_proto_rawDescData
}

var file_stock_stock_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_stock_stock_proto_goTypes = []any{
	(*GetQuoteRequest)(nil),      // 0: stock.GetQuoteRequest
	(*GetQuoteResponse)(nil),     // 1: stock.GetQuoteResponse
	(*ListQuotesRequest)(nil),    // 2: stock.ListQuotesRequest
	(*ListQuotesResponse)(nil),   // 3: stock.ListQuotesResponse
	(*SearchStocksRequest)(nil),  // 4: stock.SearchStocksRequest
	(*SearchStocksResponse)(nil), // 5: stock.SearchStocksResponse
	(*StockInfo)(nil),            // 6: stock.StockInfo
	(*ListSymbolsRequest)(nil),   // 7: stock.ListSymbolsRequest
	(*ListSymbolsResponse)(nil),  // 8: stock.ListSymbolsResponse
	(*Quote)(nil),                // 9: stock.Quote
}
var file_stock_stock_proto_depIdxs = []int32{
	9, // 0: stock.GetQuoteResponse.quote:type_name -> stock.Quote
	9, // 1: stock.ListQuotesResponse.quotes:type_name -> stock.Quote
	6, // 2: stock.SearchStocksResponse.results:type_name -> stock.StockInfo
	6, // 3: stock.ListSymbolsResponse.symbols:type_name -> stock.StockInfo
	0, // 4: stock.StockService.GetQuote:input_type -> stock.GetQuoteRequest
	2, // 5: stock.StockService.ListQuotes:input_type -> stock.ListQuotesRequest
	4, // 6: stock.StockService.SearchStocks:input_type -> stock.SearchStocksRequest
	7, // 7: stock.StockService.ListSymbols:input_type -> stock.ListSymbolsRequest
	1, // 8: stock.StockService.GetQuote:output_type -> stock.GetQuoteResponse
	3, // 9: stock.StockService.ListQuotes:output_type -> stock.ListQuotesResponse
	5, // 10: stock.StockService.SearchStocks:output_type -> stock.SearchStocksResponse
	8, // 11: stock.StockService.ListSymbols:output_type -> stock.ListSymbolsResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_stock_stock_proto_init() }
func file_stock_stock_proto_init() {
	if File_stock_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stock_stock_proto_rawDesc), len(file_stock_stock_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stock_stock_proto_goTypes,
		DependencyIndexes: file_stock_stock_proto_depIdxs,
		MessageInfos:      file_stock_stock_proto_msgTypes,
	}.Build()
	File_stock_stock_proto = out.File
	file_stock_stock_proto_goTypes = nil
	file_stock_stock_proto_depIdxs = nil
}
